version: '3.8'

services:
  crash-fuchs-app:
    build: .
    container_name: crash_fuchs_game
    ports:
      - "8080:3000"
    restart: unless-stopped
    volumes:
      - highscores_data:/app/data

volumes:
  highscores_data:
